/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.ControlJuego;
import controllers.ControlVista;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Menu extends javax.swing.JFrame {

    
    private JButton btnCrearPartida;
    private JButton btnUnirsePartida;
    private JButton btnSalir;
    private final ControlVista controlVista;
    
    public Menu(ControlVista controlVista) {
        this.controlVista = controlVista;

        setTitle("Battleship - Menú Principal");
        setSize(400, 300);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new GridLayout(3, 1, 10, 10));

        btnCrearPartida = new JButton("Crear Partida");
        btnUnirsePartida = new JButton("Unirse a Partida");
        btnSalir = new JButton("Salir");

        add(btnCrearPartida);
        add(btnUnirsePartida);
        add(btnSalir);

        initListeners();
    }

      private void initListeners() {
        btnCrearPartida.addActionListener(e -> controlVista.crearPartida());

        btnUnirsePartida.addActionListener(e -> {
            String serverId = JOptionPane.showInputDialog(
                    this,
                    "Introduce el ID del servidor",
                    "Conectar a partida",
                    JOptionPane.PLAIN_MESSAGE
            );

            if (serverId != null && !serverId.trim().isEmpty()) {
                 System.out.println("Intentando conectarme al servidor con ID: " + serverId);
                controlVista.unirseAPartida(serverId);
                
            }
        });

        btnSalir.addActionListener(e -> System.exit(0));
    }
      private void abrirPantallaAcomodo() {
        System.out.println(">>> Abriendo pantalla de acomodo...");

        Acomodo view = new Acomodo();
        view.setVisible(true);

        // Cierra la pantalla actual
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
        public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {

            // 1. Crear controlJuego
            ControlJuego controlJuego = new ControlJuego();

            // 2. Crear controlVista y vincularlo
            ControlVista controlVista = new ControlVista(controlJuego);
            controlJuego.setControlVista(controlVista);

            // 3. Crear y mostrar el menú
            Menu menu = new Menu(controlVista);
            controlVista.setMenuView(menu);

            menu.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}