/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.ControlJuego;
import controllers.ControlVista;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author Acer
 */
public class Menu extends javax.swing.JFrame {

    private final ControlVista controlVista;

    // Componentes
    private JButton btnCrearPartida;
    private JButton btnUnirsePartida;
    private JButton btnSalir;
    private JLabel lblTitulo;
    private JPanel panelPrincipal;

    public Menu(ControlVista controlVista) {
        this.controlVista = controlVista;

        // Configuración de la ventana
        setTitle("Batalla Naval - Menú Principal");
        setSize(400, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); // Centrar en pantalla

        inicializarComponentes();
    }

    private void inicializarComponentes() {
        // Panel principal con borde y color
        panelPrincipal = new JPanel();
        panelPrincipal.setLayout(new GridLayout(4, 1, 10, 10)); // 4 filas, 1 columna, espacio de 10px
        panelPrincipal.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20)); // Margen
        panelPrincipal.setBackground(new Color(50, 50, 50)); // Gris oscuro

        // Título
        lblTitulo = new JLabel("BATTLESSHIP P2P");
        lblTitulo.setFont(new Font("Arial", Font.BOLD, 24));
        lblTitulo.setForeground(Color.WHITE);
        lblTitulo.setHorizontalAlignment(SwingConstants.CENTER);

        // Botones
        btnCrearPartida = crearBotonEstilizado("Crear Partida (Host)");
        btnUnirsePartida = crearBotonEstilizado("Unirse a Partida (Cliente)");
        btnSalir = crearBotonEstilizado("Salir");

        // Listeners (Acciones)
        btnCrearPartida.addActionListener(e -> accionCrearPartida());
        btnUnirsePartida.addActionListener(e -> accionUnirsePartida());
        btnSalir.addActionListener(e -> System.exit(0));

        // Agregar al panel
        panelPrincipal.add(lblTitulo);
        panelPrincipal.add(btnCrearPartida);
        panelPrincipal.add(btnUnirsePartida);
        panelPrincipal.add(btnSalir);

        // Agregar panel a la ventana
        this.add(panelPrincipal);
    }

    private JButton crearBotonEstilizado(String texto) {
        JButton btn = new JButton(texto);
        btn.setFont(new Font("Arial", Font.PLAIN, 16));
        btn.setFocusPainted(false);
        return btn;
    }

    private void accionCrearPartida() {
        // Lógica para crear partida
        if (controlVista != null) {
            controlVista.crearPartida();
            this.dispose(); // Cerrar menú
        }
    }

    private void accionUnirsePartida() {
        // Lógica para unirse
        String serverId = JOptionPane.showInputDialog(this,
                "Introduce el ID del servidor:",
                "Conectar",
                JOptionPane.QUESTION_MESSAGE);

        if (serverId != null && !serverId.trim().isEmpty()) {
            if (controlVista != null) {
                controlVista.unirseAPartida(serverId.trim());
                this.dispose(); // Cerrar menú
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {

            // 1. Crear controlJuego
            ControlJuego controlJuego = new ControlJuego();

            // 2. Crear controlVista y vincularlo
            ControlVista controlVista = new ControlVista(controlJuego);
            controlJuego.setControlVista(controlVista);

            // 3. Crear y mostrar el menú
            Menu menu = new Menu(controlVista);

            // linea removida: controlVista.setMenuView(menu);
            menu.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
