/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.ControlJuego;
import controllers.ControlVista;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import models.Casilla;
import models.Jugador;
import models.Tablero;
import models.TableroObservador;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author Usuario
 */
public class PanelJuego extends javax.swing.JFrame implements TableroObservador{

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PanelJuego.class.getName());

    private Jugador jugador;
    private ControlVista controlVista;
    private ControlJuego controlJuego;

    public PanelJuego(Jugador jugador, ControlJuego controlJuego) {
        initComponents();
        this.jugador = jugador;
        this.controlJuego = controlJuego;

        // NO CREES un nuevo ControlVista
        // Usa el que ya tienes: controlJuego.getControlVista()
        this.controlVista = controlJuego.getControlVista();

        Tablero tablero = jugador.getTableros().get(0);
        tablero.inicializarCasillas();
        tablero.colocarNavesEnCasillas();
        tablero.addObservador(this);

        controlVista.generarTablero(tablero, panelTablero);
    }
    
      /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // Usamos el controlador, que ya inicializa todo
            ControlJuego controlJuego = new ControlJuego();
            Jugador jugador = controlJuego.getJugador();

            // Creamos la ventana
            PanelJuego panel = new PanelJuego(jugador, controlJuego);
            panel.setVisible(true);
        });
    }

    public void actualizarTablero(Tablero tablero, String mensaje) {
        // Actualiza los íconos de los botones según el estado del modelo
        controlVista.actualizarBotones(tablero);

        // Puedes imprimir el mensaje de notificación si quieres
        System.out.println("Notificación recibida: " + mensaje);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTablero = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1400, 800));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTablero.setOpaque(false);
        panelTablero.setLayout(null);
        getContentPane().add(panelTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 600, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PantallaJuego.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelTablero;
    // End of variables declaration//GEN-END:variables

}
